version: '3.9'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - ${MYSQL_PORT}:3306

  cache:
    image: redis:latest
    environment:
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: 6379
      REDIS_DB: '${REDIS_DB}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    ports:
      - ${REDIS_PORT}:6379
